### ISSUE TITLE
HTTP Error 308: Permanent Redirect while downloading database

### ISSUE THREAD

**Issue by naveedunjum** [iconclass/data#27]
While using the library for the first time, the download is not working. It gives HTTP Error 308.

![image](https://user-images.githubusercontent.com/37370766/184358344-fb131cf7-a423-4ace-a6f5-47da81e07d4b.png)

Is there some way I can refer to the database on my system which I downloaded manually.?

**Comment by epoz** [comment]
Hi Naveed, 

This is a bug, earlier this year I switched over to https:// for the Iconclass site, and it looks like the re-direct is not being followed.

The library looks for a file named `iconclass.sqlite` in the current directory, and if it is not found, then tries to download it from that URL.

So if you download the file manually, and then rename it, that should fix the error.

**Comment by epoz** [comment]
What you could also do, is to clone this repo, and then run the script `make_sqlite.py` - that also generates a "fresh" database with the latest data in it.

**Comment by naveedunjum** [comment]
Hey, Thanks for getting back. This works well. 
I had also figured a hack. I needed only the english text, therefore used the text files in this repo to manually create a dictionary.  Thanks for this amazing resource.
